export const ACTION_TYPE = {
	SET_USER: 'SET_USER',
	LOGOUT: 'LOGOUT',
	SET_PROJECT_DATA: 'SET_PROJECT_DATA',
	SET_PROJECTS: 'SET_PROJECTS',
	ADD_TASK: 'ADD_TASK',
	REMOVE_TASK: 'REMOVE_TASK',
	OPEN_MODAL: 'OPEN_MODAL',
	OPEN_MODAL_PROFILE: 'OPEN_MODAL_PROFILE',
	CLOSE_MODAL: 'CLOSE_MODAL',
};
